baseURL = "https://datascisocial.github.io/blog/"
languageCode = "en-us"
title = "datasci.social"
theme = "hugo-ink"
paginate = 6

copyright = "Â© datasci.social"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
	subtitle = "updates for the [mastodon server](https://datasci.social/)"

	# Optional 64x64 avatar image.
	avatar = "https://datascisocial.github.io/blog/images/logodatascisocial_square.png"
	
	featherIconsCDN = true

	mode = "auto" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/datascisocial/blog/"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/blog/index.xml"

[taxonomies]
   tag = "tags"
